# Generated by Django 2.0.1 on 2018-02-27 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20180227_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='creation',
        ),
        migrations.DeleteModel(
            name='Picture',
        ),
    ]
